window.INTEL=[];
// Live intelligence is loaded by js/live.js (12h auto-sync). Demo data removed in v21.
window.CROSS_BORDER=[
{from:[44.36,33.31],to:[54.37,24.45],label:"Regional AML/CFT"},
{from:[-77.03,38.90],to:[-0.12,51.50],label:"Sanctions / Enforcement"},
{from:[103.81,1.35],to:[44.36,33.31],label:"Cyber-enabled Financial Crime"}
];

window.REUTERS=[
{title:"AML enforcement and banking controls",topic:"AML / Banking"},
{title:"Sanctions and cross-border restrictions",topic:"Sanctions"},
{title:"Cyber-enabled fraud and financial crime",topic:"Cybercrime / Fraud"},
{title:"Regulatory action involving financial institutions",topic:"Enforcement"},
{title:"Global money-laundering developments",topic:"AML/CFT"}
];

window.FIXED_BRIEFS={
fatf:{title:"FATF — Latest Update",meta:"Official Source",tags:["FATF","AML/CFT"],english:"This permanent brief is designed to explain the newest FATF development in practical terms: what was published, what changed, which jurisdictions or sectors are affected, and what AML/CFT teams may need to review.",impact:"May affect country-risk scoring, EDD, transaction monitoring, correspondent relationships and internal AML/CFT policies.",arabic:"هذا الموجز الثابت مخصص لشرح آخر تطور صادر عن مجموعة العمل المالي FATF بصورة عملية: ما الذي تم نشره، وما الذي تغير، وما هي الدول أو القطاعات المتأثرة، وما الذي قد تحتاج فرق مكافحة غسل الأموال وتمويل الإرهاب إلى مراجعته.",url:"https://www.fatf-gafi.org/"},
sanctions:{title:"Sanctions — Latest Update",meta:"Official Sanctions Sources",tags:["Sanctions","Screening"],english:"This brief is reserved for new sanctions designations, amendments and removals from approved official authorities, with focus on potential screening and exposure impact.",impact:"Confirmed list changes can require prompt rescreening and escalation of potential matches.",arabic:"هذا الموجز مخصص لأحدث الإضافات والتعديلات والحذف من قوائم العقوبات الرسمية، مع توضيح التأثير المحتمل على الفحص والتعرض للأطراف الخاضعة للعقوبات.",url:"https://ofac.treasury.gov/"},
aml:{title:"AML / CFT — Global Watch",meta:"Multi-Source",tags:["AML","CFT","FinCrime"],english:"A global operational brief covering regulators, FIUs, FATF-style regional bodies, central banks, law enforcement, virtual assets, terrorist financing and emerging laundering typologies.",impact:"Provides a single operational view of the most important global AML/CFT developments.",arabic:"موجز تشغيلي عالمي يغطي الجهات الرقابية ووحدات المعلومات المالية والهيئات الإقليمية والبنوك المركزية وإنفاذ القانون والأصول الافتراضية وتمويل الإرهاب والأنماط المستجدة لغسل الأموال.",url:"https://www.fatf-gafi.org/"},
iqtfs:{title:"IQTFS — Iraq Sanctions Watch",meta:"Official Iraqi AML/CFT Office Source",tags:["IQTFS","Iraq","Sanctions","Freezing"],english:"This permanent brief is dedicated to IQTFS, the Iraqi AML/CFT sanctions platform operated through the Office of Combating Money Laundering and Terrorist Financing. It is intended to surface updates to Iraqi local sanctions lists, freezing decisions, appeals or related notices, as well as international and United Nations sanctions material published through the Iraqi platform. In production, every new version would be compared with the previous stored version so additions, amendments and removals are immediately visible.",impact:"Because these are Iraq-facing official sanctions and freezing updates, confirmed changes may require immediate screening, escalation and operational action under applicable Iraqi requirements.",arabic:"هذا الموجز الثابت مخصص لمنصة IQTFS العراقية لعقوبات مكافحة غسل الأموال وتمويل الإرهاب التابعة لمكتب مكافحة غسل الأموال وتمويل الإرهاب. الغرض منه إظهار تحديثات قوائم العقوبات المحلية العراقية وقرارات التجميد والطعون أو الإشعارات ذات الصلة، إضافة إلى مواد العقوبات الدولية وقوائم مجلس الأمن المنشورة عبر المنصة العراقية. في النسخة الفعلية ستتم مقارنة كل نسخة جديدة بالنسخة السابقة لإظهار الإضافات والتعديلات والحذف فوراً.",url:"https://aml.iq/?page_id=2288"},
reuters:{title:"Reuters — Financial Crime Watch",meta:"Trusted Media",tags:["Reuters","Trusted Media"],english:"Reuters reporting directly related to AML/CFT, sanctions, bank enforcement, fraud, cyber-enabled financial crime and cross-border investigations. Primary official sources should remain authoritative.",impact:"Useful for fast context and cross-border reporting while official sources remain authoritative.",arabic:"تقارير رويترز المرتبطة مباشرة بمكافحة غسل الأموال وتمويل الإرهاب والعقوبات وقضايا البنوك والاحتيال والجرائم المالية الإلكترونية والتحقيقات العابرة للحدود، مع بقاء المصادر الرسمية هي المرجع المعتمد.",url:"https://www.reuters.com/"}
};