window.INTEL=[
{id:1,country:"Iraq",countryKey:"Iraq",coord:[44.36,33.31],layer:"fatf",source:"MENAFATF",body:"MENAFATF",date:"2026-08-11",priority:"High",title:"MENAFATF-related AML/CFT update indexed for Iraq",summary:"Regional AML/CFT material linked to Iraq for country-risk and compliance monitoring.",brief:"A regional AML/CFT development has been linked to Iraq. The production version would explain what was published, whether it relates to follow-up, evaluation, technical compliance, effectiveness or supervisory expectations, and how it may affect country-risk scoring, enhanced due diligence, correspondent relationships and transaction monitoring.",impact:"Potentially relevant to geographic risk scoring, EDD, monitoring scenarios and cross-border controls.",ar:"تم ربط تطور إقليمي يتعلق بمكافحة غسل الأموال وتمويل الإرهاب بالعراق. في النسخة الفعلية سيشرح النظام ما الذي تم نشره وما إذا كان يتعلق بالمتابعة أو التقييم أو الالتزام الفني أو الفعالية أو التوقعات الرقابية وتأثيره المحتمل على مخاطر الدول والعناية الواجبة المعززة والعلاقات المصرفية ومراقبة المعاملات.",url:"https://menafatf.org/"},
{id:2,country:"Iraq",countryKey:"Iraq",coord:[44.36,33.31],layer:"banking",source:"Central Bank of Iraq",body:"CBI",date:"2026-08-10",priority:"High",title:"Iraq banking regulatory item detected",summary:"Regulatory intelligence classified for operational compliance review.",brief:"A banking-regulatory item has been detected for Iraq and would be analysed for effective dates, affected products, institutions, obligations, reporting requirements and implementation impact.",impact:"May affect procedures, reporting, customer controls, product rules or governance.",ar:"تم رصد تحديث رقابي مصرفي يتعلق بالعراق وسيتم تحليله لتحديد تاريخ النفاذ والمنتجات والجهات المتأثرة والمتطلبات ومتطلبات الإبلاغ والأثر التشغيلي.",url:"https://cbi.iq/"},
{id:3,country:"Cayman Islands",countryKey:"Cayman Islands",coord:[-81.25,19.31],layer:"fatf",source:"CFATF",body:"CFATF",date:"2026-08-11",priority:"Medium",title:"CFATF monitoring item linked to Cayman Islands",summary:"Caribbean AML/CFT intelligence linked to CFATF and jurisdictional monitoring.",brief:"This item shows how a Caribbean jurisdiction is connected to CFATF, FATF, sanctions and tax-transparency intelligence in one country profile.",impact:"Relevant to geographic risk, correspondent banking and cross-border controls.",ar:"يوضح هذا المثال كيفية ربط دولة من دول الكاريبي بمصادر CFATF وFATF والعقوبات والشفافية الضريبية ضمن ملف دولة موحد.",url:"https://www.cfatf-gafic.org/"},
{id:4,country:"Bahamas",countryKey:"The Bahamas",coord:[-77.39,25.03],layer:"fatca",source:"IRS",body:"FATCA",date:"2026-08-10",priority:"Medium",title:"FATCA / tax-transparency update linked to Bahamas",summary:"Tax-transparency intelligence linked to the Bahamas.",brief:"A FATCA or tax-transparency development has been linked to the Bahamas profile and kept as a distinct but searchable compliance domain.",impact:"May affect onboarding documentation, tax classification and reporting.",ar:"تم ربط تطور متعلق بـFATCA أو الشفافية الضريبية بملف جزر البهاما مع إبقائه ضمن مجال امتثال مستقل وقابل للبحث.",url:"https://www.irs.gov/"},
{id:5,country:"United States",countryKey:"United States of America",coord:[-77.03,38.90],layer:"sanctions",source:"OFAC",body:"OFAC",date:"2026-08-11",priority:"Critical",title:"Sanctions designation change detected",summary:"Official sanctions-list change flagged for screening review.",brief:"A sanctions-list change has been flagged. Production mode would compare additions, amendments and removals and identify potential customer, beneficiary, merchant or counterparty exposure.",impact:"Can require immediate rescreening, exposure review and escalation of potential matches.",ar:"تم رصد تغيير في قائمة عقوبات رسمية. في النسخة الفعلية سيقارن النظام الإضافات والتعديلات والحذف ويحدد التأثير المحتمل على فحص العملاء والمستفيدين والتجار والأطراف المقابلة.",url:"https://ofac.treasury.gov/"},
{id:6,country:"United Kingdom",countryKey:"United Kingdom",coord:[-0.12,51.50],layer:"aml",source:"FATF",body:"FATF",date:"2026-08-09",priority:"Medium",title:"FATF publication indexed for UK-related monitoring",summary:"FATF material linked to the UK intelligence profile.",brief:"A FATF publication has been connected to the United Kingdom country view so analysts can see global-standard developments alongside domestic regulatory and sanctions intelligence.",impact:"Helps connect global FATF standards with domestic compliance obligations.",ar:"تم ربط منشور صادر عن FATF بملف المملكة المتحدة حتى يتمكن المحلل من مشاهدة التطورات العالمية إلى جانب التحديثات المحلية والعقوبات.",url:"https://www.fatf-gafi.org/"},
{id:7,country:"Jordan",countryKey:"Jordan",coord:[35.91,31.95],layer:"egmont",source:"Egmont Group",body:"Egmont",date:"2026-08-08",priority:"Medium",title:"Egmont-related FIU cooperation material",summary:"Public FIU cooperation and typology intelligence.",brief:"Public Egmont Group material is indexed as FIU-related intelligence and linked to jurisdictions without implying access to confidential FIU data.",impact:"Supports typology awareness and FIU cooperation monitoring.",ar:"تتم فهرسة المواد العلنية الصادرة عن مجموعة إيغمونت ضمن معلومات وحدات الاستخبارات المالية وربطها بالدول دون الإيحاء بالوصول إلى معلومات سرية.",url:"https://egmontgroup.org/"},
{id:8,country:"Singapore",countryKey:"Singapore",coord:[103.81,1.35],layer:"cyber",source:"INTERPOL",body:"INTERPOL",date:"2026-08-11",priority:"High",title:"Cross-border cyber-enabled financial crime operation",summary:"Law-enforcement intelligence on cyber-enabled fraud and financial crime.",brief:"A cyber-enabled financial crime operation has been indexed with focus on typologies, jurisdictions, published indicators and relevance to fraud and AML controls.",impact:"Useful for mule-account detection, phishing controls, fraud rules and transaction monitoring.",ar:"تمت فهرسة عملية تتعلق بجريمة مالية مدعومة إلكترونياً مع التركيز على الأنماط والدول والمؤشرات المنشورة وعلاقتها بضوابط مكافحة الاحتيال وغسل الأموال.",url:"https://www.interpol.int/Crimes/Cybercrime"},
{id:9,country:"United Arab Emirates",countryKey:"United Arab Emirates",coord:[54.37,24.45],layer:"enforcement",source:"Regulatory Enforcement",body:"MENAFATF",date:"2026-08-11",priority:"High",title:"Regional enforcement development affecting financial institutions",summary:"Enforcement-related financial crime intelligence linked to the UAE profile.",brief:"The platform can link enforcement cases to the relevant jurisdiction, sector, institution type and financial-crime theme while keeping official sources authoritative.",impact:"May affect risk appetite, peer benchmarking and control expectations.",ar:"يمكن للمنصة ربط قضايا الإنفاذ بالدولة والقطاع ونوع المؤسسة وموضوع الجريمة المالية مع إبقاء المصادر الرسمية هي المرجع المعتمد.",url:"https://menafatf.org/"},
{id:10,country:"Germany",countryKey:"Germany",coord:[13.40,52.52],layer:"aml",source:"MONEYVAL / EU",body:"MONEYVAL",date:"2026-08-07",priority:"Medium",title:"European AML supervisory development",summary:"European AML/CFT supervisory intelligence linked to Germany.",brief:"A European AML/CFT item is indexed to demonstrate regional-body and domestic-source aggregation.",impact:"May affect supervisory expectations and cross-border compliance monitoring.",ar:"تمت فهرسة مادة أوروبية مرتبطة بمكافحة غسل الأموال وتمويل الإرهاب لإظهار كيفية جمع المصادر الإقليمية والمحلية ضمن ملف دولة واحد.",url:"https://www.coe.int/en/web/moneyval"},
{id:11,country:"Argentina",countryKey:"Argentina",coord:[-58.38,-34.60],layer:"fatf",source:"GAFILAT",body:"GAFILAT",date:"2026-08-06",priority:"Medium",title:"GAFILAT follow-up intelligence linked to Argentina",summary:"Latin American FATF-style regional body monitoring item.",brief:"Country intelligence can aggregate GAFILAT follow-up, domestic FIU, regulator and enforcement material in one view.",impact:"Useful for geographic risk and regional AML/CFT monitoring.",ar:"يمكن لملف الدولة جمع مواد المتابعة الصادرة عن GAFILAT ووحدة المعلومات المالية والجهات الرقابية وإنفاذ القانون في صفحة واحدة.",url:"https://www.gafilat.org/"},
{id:12,country:"Nigeria",countryKey:"Nigeria",coord:[7.49,9.07],layer:"fatf",source:"GIABA",body:"GIABA",date:"2026-08-05",priority:"Medium",title:"GIABA regional AML/CFT monitoring item",summary:"West African regional AML/CFT intelligence linked to Nigeria.",brief:"This demonstrates GIABA-linked country monitoring and regional risk intelligence.",impact:"Relevant to regional risk assessment and correspondent monitoring.",ar:"يوضح هذا المثال ربط معلومات GIABA بملف الدولة وتقييم المخاطر الإقليمية.",url:"https://www.giaba.org/"},
{id:13,country:"Iraq",countryKey:"Iraq",coord:[44.36,33.31],layer:"iqtfs",source:"IQTFS — Iraq Sanctions Platform",body:"IQTFS",date:"2026-08-11",priority:"Critical",title:"IQTFS local sanctions / freezing list update detected",summary:"Official Iraqi sanctions-platform update reserved for local designations, freezing decisions and related notices.",brief:"A new item has been detected from IQTFS, the Iraqi AML/CFT sanctions platform operated through the Office of Combating Money Laundering and Terrorist Financing. In production, the system would compare the newly retrieved list or notice against the previous stored version, identify additions, amendments, removals, freezing decisions and relevant dates, then generate an operational brief for screening and compliance teams.",impact:"A confirmed Iraqi local designation or freezing decision can require immediate screening, escalation, restriction or freezing actions in line with applicable Iraqi requirements.",ar:"تم رصد تحديث جديد من منصة العراق لعقوبات مكافحة غسل الأموال وتمويل الإرهاب IQTFS التابعة لمكتب مكافحة غسل الأموال وتمويل الإرهاب. في النسخة الفعلية سيقارن النظام القائمة أو الإشعار الجديد بالنسخة السابقة ويحدد الإضافات والتعديلات والحذف وقرارات التجميد والتواريخ ذات الصلة، ثم يعد موجزاً تشغيلياً لفرق الفحص والامتثال.",url:"https://aml.iq/?page_id=2288"},
{id:14,country:"Iraq",countryKey:"Iraq",coord:[44.36,33.31],layer:"iqtfs",source:"IQTFS — Iraq Sanctions Platform",body:"IQTFS",date:"2026-08-10",priority:"High",title:"IQTFS international / UN sanctions list notice indexed",summary:"International sanctions notice published through the Iraqi AML/CFT sanctions platform.",brief:"The Iraqi sanctions platform also provides access to international sanctions-related material, including United Nations Security Council sanctions information and freezing-related implementation content. The production system would treat these as a dedicated Iraq-facing sanctions feed and preserve the original source for audit and verification.",impact:"International sanctions updates published through the Iraqi platform may require rapid rescreening and review of customer or counterparty exposure.",ar:"تتضمن منصة العقوبات العراقية كذلك مواد مرتبطة بالعقوبات الدولية، بما في ذلك قوائم وقرارات مجلس الأمن ذات الصلة وآليات تنفيذ قرارات التجميد. في النسخة الفعلية سيتم التعامل معها كمصدر عراقي رسمي مستقل مع الاحتفاظ بالمصدر الأصلي لأغراض التدقيق والتحقق.",url:"https://aml.iq/?page_id=2288"}
];

window.CROSS_BORDER=[
{from:[44.36,33.31],to:[54.37,24.45],label:"Regional AML/CFT"},
{from:[-77.03,38.90],to:[-0.12,51.50],label:"Sanctions / Enforcement"},
{from:[103.81,1.35],to:[44.36,33.31],label:"Cyber-enabled Financial Crime"}
];

window.REUTERS=[
{title:"AML enforcement and banking controls",topic:"AML / Banking"},
{title:"Sanctions and cross-border restrictions",topic:"Sanctions"},
{title:"Cyber-enabled fraud and financial crime",topic:"Cybercrime / Fraud"},
{title:"Regulatory action involving financial institutions",topic:"Enforcement"},
{title:"Global money-laundering developments",topic:"AML/CFT"}
];

window.FIXED_BRIEFS={
fatf:{title:"FATF — Latest Update",meta:"Official Source",tags:["FATF","AML/CFT"],english:"This permanent brief is designed to explain the newest FATF development in practical terms: what was published, what changed, which jurisdictions or sectors are affected, and what AML/CFT teams may need to review.",impact:"May affect country-risk scoring, EDD, transaction monitoring, correspondent relationships and internal AML/CFT policies.",arabic:"هذا الموجز الثابت مخصص لشرح آخر تطور صادر عن مجموعة العمل المالي FATF بصورة عملية: ما الذي تم نشره، وما الذي تغير، وما هي الدول أو القطاعات المتأثرة، وما الذي قد تحتاج فرق مكافحة غسل الأموال وتمويل الإرهاب إلى مراجعته.",url:"https://www.fatf-gafi.org/"},
sanctions:{title:"Sanctions — Latest Update",meta:"Official Sanctions Sources",tags:["Sanctions","Screening"],english:"This brief is reserved for new sanctions designations, amendments and removals from approved official authorities, with focus on potential screening and exposure impact.",impact:"Confirmed list changes can require prompt rescreening and escalation of potential matches.",arabic:"هذا الموجز مخصص لأحدث الإضافات والتعديلات والحذف من قوائم العقوبات الرسمية، مع توضيح التأثير المحتمل على الفحص والتعرض للأطراف الخاضعة للعقوبات.",url:"https://ofac.treasury.gov/"},
aml:{title:"AML / CFT — Global Watch",meta:"Multi-Source",tags:["AML","CFT","FinCrime"],english:"A global operational brief covering regulators, FIUs, FATF-style regional bodies, central banks, law enforcement, virtual assets, terrorist financing and emerging laundering typologies.",impact:"Provides a single operational view of the most important global AML/CFT developments.",arabic:"موجز تشغيلي عالمي يغطي الجهات الرقابية ووحدات المعلومات المالية والهيئات الإقليمية والبنوك المركزية وإنفاذ القانون والأصول الافتراضية وتمويل الإرهاب والأنماط المستجدة لغسل الأموال.",url:"https://www.fatf-gafi.org/"},
iqtfs:{title:"IQTFS — Iraq Sanctions Watch",meta:"Official Iraqi AML/CFT Office Source",tags:["IQTFS","Iraq","Sanctions","Freezing"],english:"This permanent brief is dedicated to IQTFS, the Iraqi AML/CFT sanctions platform operated through the Office of Combating Money Laundering and Terrorist Financing. It is intended to surface updates to Iraqi local sanctions lists, freezing decisions, appeals or related notices, as well as international and United Nations sanctions material published through the Iraqi platform. In production, every new version would be compared with the previous stored version so additions, amendments and removals are immediately visible.",impact:"Because these are Iraq-facing official sanctions and freezing updates, confirmed changes may require immediate screening, escalation and operational action under applicable Iraqi requirements.",arabic:"هذا الموجز الثابت مخصص لمنصة IQTFS العراقية لعقوبات مكافحة غسل الأموال وتمويل الإرهاب التابعة لمكتب مكافحة غسل الأموال وتمويل الإرهاب. الغرض منه إظهار تحديثات قوائم العقوبات المحلية العراقية وقرارات التجميد والطعون أو الإشعارات ذات الصلة، إضافة إلى مواد العقوبات الدولية وقوائم مجلس الأمن المنشورة عبر المنصة العراقية. في النسخة الفعلية ستتم مقارنة كل نسخة جديدة بالنسخة السابقة لإظهار الإضافات والتعديلات والحذف فوراً.",url:"https://aml.iq/?page_id=2288"},
reuters:{title:"Reuters — Financial Crime Watch",meta:"Trusted Media",tags:["Reuters","Trusted Media"],english:"Reuters reporting directly related to AML/CFT, sanctions, bank enforcement, fraud, cyber-enabled financial crime and cross-border investigations. Primary official sources should remain authoritative.",impact:"Useful for fast context and cross-border reporting while official sources remain authoritative.",arabic:"تقارير رويترز المرتبطة مباشرة بمكافحة غسل الأموال وتمويل الإرهاب والعقوبات وقضايا البنوك والاحتيال والجرائم المالية الإلكترونية والتحقيقات العابرة للحدود، مع بقاء المصادر الرسمية هي المرجع المعتمد.",url:"https://www.reuters.com/"}
};