window.INTEL=[
{id:1,country:"Iraq",coord:[44.36,33.31],layer:"fatf",source:"MENAFATF",date:"2026-08-11",title:"MENAFATF-related AML/CFT update indexed for Iraq",summary:"Regional AML/CFT material linked to Iraq for country-risk and compliance monitoring.",brief:"A regional AML/CFT development has been linked to Iraq. The production version would explain what was published, whether it relates to follow-up, evaluation, technical compliance or supervisory expectations, and how it may affect country-risk scoring, enhanced due diligence and transaction monitoring.",ar:"تم ربط تطور إقليمي يتعلق بمكافحة غسل الأموال وتمويل الإرهاب بالعراق. في النسخة الفعلية سيشرح النظام ما الذي تم نشره وما إذا كان يتعلق بالمتابعة أو التقييم أو الالتزام الفني أو التوقعات الرقابية وتأثيره المحتمل على مخاطر الدول والعناية الواجبة ومراقبة المعاملات.",url:"https://menafatf.org/"},
{id:2,country:"Iraq",coord:[44.36,33.31],layer:"banking",source:"Central Bank of Iraq",date:"2026-08-10",title:"Iraq banking regulatory item detected",summary:"Regulatory intelligence classified for operational compliance review.",brief:"A banking-regulatory item has been detected for Iraq and would be analysed for effective dates, affected products, institutions, obligations and implementation impact.",ar:"تم رصد تحديث رقابي مصرفي يتعلق بالعراق وسيتم تحليله لتحديد تاريخ النفاذ والمنتجات والجهات المتأثرة والمتطلبات والأثر التشغيلي.",url:"https://cbi.iq/"},
{id:3,country:"Cayman Islands",coord:[-81.25,19.31],layer:"fatf",source:"CFATF",date:"2026-08-11",title:"CFATF monitoring item linked to Cayman Islands",summary:"Caribbean AML/CFT intelligence linked to CFATF and jurisdictional monitoring.",brief:"This item shows how a Caribbean jurisdiction is connected to CFATF, FATF, sanctions and tax-transparency intelligence in one country profile.",ar:"يوضح هذا المثال كيفية ربط دولة من دول الكاريبي بمصادر CFATF وFATF والعقوبات والشفافية الضريبية ضمن ملف دولة موحد.",url:"https://www.cfatf-gafic.org/"},
{id:4,country:"Bahamas",coord:[-77.39,25.03],layer:"fatca",source:"IRS",date:"2026-08-10",title:"FATCA / tax-transparency update linked to Bahamas",summary:"Tax-transparency intelligence linked to the Bahamas.",brief:"A FATCA or tax-transparency development has been linked to the Bahamas profile and kept as a distinct but searchable compliance domain.",ar:"تم ربط تطور متعلق بـFATCA أو الشفافية الضريبية بملف جزر البهاما مع إبقائه ضمن مجال امتثال مستقل وقابل للبحث.",url:"https://www.irs.gov/"},
{id:5,country:"United States",coord:[-77.03,38.90],layer:"sanctions",source:"OFAC",date:"2026-08-11",title:"Sanctions designation change detected",summary:"Official sanctions-list change flagged for screening review.",brief:"A sanctions-list change has been flagged. Production mode would compare additions, amendments and removals and identify potential customer, beneficiary, merchant or counterparty exposure.",ar:"تم رصد تغيير في قائمة عقوبات رسمية. في النسخة الفعلية سيقارن النظام الإضافات والتعديلات والحذف ويحدد التأثير المحتمل على فحص العملاء والمستفيدين والتجار والأطراف المقابلة.",url:"https://ofac.treasury.gov/"},
{id:6,country:"United Kingdom",coord:[-0.12,51.50],layer:"aml",source:"FATF",date:"2026-08-09",title:"FATF publication indexed for UK-related monitoring",summary:"FATF material linked to the UK intelligence profile.",brief:"A FATF publication has been connected to the United Kingdom country view so analysts can see global-standard developments alongside domestic regulatory and sanctions intelligence.",ar:"تم ربط منشور صادر عن FATF بملف المملكة المتحدة حتى يتمكن المحلل من مشاهدة التطورات العالمية إلى جانب التحديثات المحلية والعقوبات.",url:"https://www.fatf-gafi.org/"},
{id:7,country:"Jordan",coord:[35.91,31.95],layer:"egmont",source:"Egmont Group",date:"2026-08-08",title:"Egmont-related FIU cooperation material",summary:"Public FIU cooperation and typology intelligence.",brief:"Public Egmont Group material is indexed as FIU-related intelligence and linked to jurisdictions without implying access to confidential FIU data.",ar:"تتم فهرسة المواد العلنية الصادرة عن مجموعة إيغمونت ضمن معلومات وحدات الاستخبارات المالية وربطها بالدول دون الإيحاء بالوصول إلى معلومات سرية.",url:"https://egmontgroup.org/"},
{id:8,country:"Singapore",coord:[103.81,1.35],layer:"cyber",source:"INTERPOL",date:"2026-08-11",title:"Cross-border cyber-enabled financial crime operation",summary:"Law-enforcement intelligence on cyber-enabled fraud and financial crime.",brief:"A cyber-enabled financial crime operation has been indexed with focus on typologies, jurisdictions, published indicators and relevance to fraud and AML controls.",ar:"تمت فهرسة عملية تتعلق بجريمة مالية مدعومة إلكترونياً مع التركيز على الأنماط والدول والمؤشرات المنشورة وعلاقتها بضوابط مكافحة الاحتيال وغسل الأموال.",url:"https://www.interpol.int/Crimes/Cybercrime"}
];
window.REUTERS=[
{title:"AML enforcement and banking controls",topic:"AML / Banking"},
{title:"Sanctions and cross-border restrictions",topic:"Sanctions"},
{title:"Cyber-enabled fraud and financial crime",topic:"Cybercrime / Fraud"},
{title:"Regulatory action involving financial institutions",topic:"Enforcement"},
{title:"Global money-laundering developments",topic:"AML/CFT"}
];